import mongoose from 'mongoose';

const alertSchema = new mongoose.Schema({
  type: {
    type: String,
    required: true,
    enum: ['critical', 'warning', 'info', 'success']
  },
  priority: {
    type: String,
    enum: ['Low', 'Medium', 'High', 'Critical'],
    default: 'Medium'
  },
  title: {
    type: String,
    required: [true, 'Please add alert title'],
    maxlength: [100, 'Title cannot be more than 100 characters']
  },
  message: {
    type: String,
    required: [true, 'Please add alert message'],
    maxlength: [500, 'Message cannot be more than 500 characters']
  },
  vehicle: {
    type: mongoose.Schema.ObjectId,
    ref: 'Vehicle'
  },
  driver: {
    type: mongoose.Schema.ObjectId,
    ref: 'Driver'
  },
  trip: {
    type: mongoose.Schema.ObjectId,
    ref: 'Trip'
  },
  maintenance: {
    type: mongoose.Schema.ObjectId,
    ref: 'Maintenance'
  },
  status: {
    type: String,
    enum: ['Active', 'Acknowledged', 'Resolved'],
    default: 'Active'
  },
  acknowledgedBy: {
    type: mongoose.Schema.ObjectId,
    ref: 'User'
  },
  acknowledgedAt: {
    type: Date
  },
  resolvedBy: {
    type: mongoose.Schema.ObjectId,
    ref: 'User'
  },
  resolvedAt: {
    type: Date
  },
  dueDate: {
    type: Date
  },
  metadata: {
    type: mongoose.Schema.Types.Mixed // For additional alert-specific data
  },
  autoGenerated: {
    type: Boolean,
    default: false
  },
  createdBy: {
    type: mongoose.Schema.ObjectId,
    ref: 'User'
  }
}, {
  timestamps: true,
  toJSON: { virtuals: true },
  toObject: { virtuals: true }
});

// Index for better query performance
alertSchema.index({ type: 1 });
alertSchema.index({ priority: 1 });
alertSchema.index({ status: 1 });
alertSchema.index({ vehicle: 1 });
alertSchema.index({ driver: 1 });
alertSchema.index({ createdAt: -1 });

// Virtual for days until due
alertSchema.virtual('daysUntilDue').get(function() {
  if (!this.dueDate) return null;
  const now = new Date();
  const diffTime = this.dueDate - now;
  return Math.ceil(diffTime / (1000 * 60 * 60 * 24));
});

// Instance method to acknowledge alert
alertSchema.methods.acknowledge = function(userId) {
  this.status = 'Acknowledged';
  this.acknowledgedBy = userId;
  this.acknowledgedAt = new Date();
  return this.save();
};

// Instance method to resolve alert
alertSchema.methods.resolve = function(userId) {
  this.status = 'Resolved';
  this.resolvedBy = userId;
  this.resolvedAt = new Date();
  return this.save();
};

// Static method to create vehicle-related alerts
alertSchema.statics.createVehicleAlert = async function(vehicleId, alertData) {
  const alert = new this({
    ...alertData,
    vehicle: vehicleId,
    autoGenerated: true
  });
  return alert.save();
};

// Static method to create maintenance-related alerts
alertSchema.statics.createMaintenanceAlert = async function(maintenanceId, alertData) {
  const alert = new this({
    ...alertData,
    maintenance: maintenanceId,
    autoGenerated: true
  });
  return alert.save();
};

export default mongoose.model('Alert', alertSchema);